### ISSUE TITLE
Are you gonna do how-to-npm and learnyounode?

### ISSUE THREAD

**Issue by yumkimun** [netbun/nodeschool-cheatsheet#1]
the javascripting answers helped me alot but are you gonna do how-to-npm or learnyounode?

**Comment by netbun** [comment]
@yumkimun I attempted to do learnyounode and how-to-npm, but these workshops seem to be broken in a way but I'll try to find a work around so more resources will be added to this repo :smile:

**Comment by yumkimun** [comment]
@netbun Okay man, thanks
